### ISSUE TITLE
Assert data type error

### ISSUE THREAD

**Issue by phoenix5485** [freespace/pyAPT#10]
Hello I'm working on adapting this code to work with a Thorlabs k-cube piezo controller for a project for my Masters degree. While, I can use it to identify the controllers I got the following error when I tried to set the drive voltage: 

File "/usr/local/home/labuser/pyAPT/pyAPT/controller.py:, line 536, in opset
   setmsg = Message(message.MGMSG_PZ_SET_OUTPUTVOLTS, data=setpar)
File"/usr/local/home/labuser/pyAPT/pyAPT/message.py:, line 66, in __new__
   assert(type(data) in [list, tuple, str])
AssertionError

Did the data type for the variables handled in the coms protocols need to be predefined in the controller code or do I need to modify the code in the message code? 

I've attached copies of my set voltage code as well as the modified controller code. 

Any assistance would be greatly appreciated.

[code.zip](https://github.com/freespace/pyAPT/files/2756395/code.zip)

**Comment by phoenix5485** [comment]
Ok, I updated the repository and it did resolve, however another error popped up in message.py 

TypeError: 'type' object is not iterable, traceback line 68 in message.py: 
         data = list(bytes)

Error resolved by following modification to message.py line 68:  
         data = list(bytes)  ->  data = [bytes] 
The error in line 68 cleared after this change, however an error in line 112 of message.py popped up after the change. 

message.py, line 112, in pack *datalist) 

struct.error: required argument is not an integer 

Did my modification cause this, is it a problem with the format characters or something else?

**Comment by freespace** [comment]
Ah it should have been `list(data)` not `list(bytes)`. I have pushed a commit to fix this. Please discard your changes and update.

**Comment by phoenix5485** [comment]
I think that fixed it, thank you for your assistance. If I have any further issues I will let you know.
