### ISSUE TITLE
Other project

### ISSUE THREAD

**Issue by lfasnacht** [freespace/pyAPT#3]
Hello!

I'm currently working on an alternative implementation of Thorlab's APT protocol in Python, which can be found on: https://github.com/UniNE-CHYN/thorpy

My code is GPL-2 licensed, which is not compatible with the MIT license you use, but feel free to borrow ideas for your implementation.

Since I don't have access to many stage/controllers, I would greatly appreciate any feedback/contribution.

Thanks a lot,

Laurent

Laurent

**Comment by freespace** [comment]
Hi Laurent!

Very nice code! Seems a lot more comprehensive than mine, and structured better :)

I will be sure to test it out when I have some new stages (and time, the enemy of the PhD student).

Cheers,
Steve
