### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by israelcass** [freespace/pyAPT#9]
I trying to use your code on linux but I got some problems.
When I connect the device on Ubuntu, I've got:

new full-speed USB device number 15 using ehci-pci
New USB device found, idVendor=0403, idProduct=faf0
New USB device strings: Mfr=1, Product=2, **SerialNumber=3**
usb 3-1.2.5: Product: APT Piezo Controller
Manufacturer: Thorlabs
usb 3-1.2.5: SerialNumber: **81846609**
ftdi_sio 3-1.2.5:1.0: FTDI USB Serial Device converter detected
usb 3-1.2.5: Detected FT232BM
usb 3-1.2.5: FTDI USB Serial Device converter now attached to **ttyUSB4**
usb 3-1.2.6: new full-speed USB device number 16 using ehci-pci
usb 3-1.2.6: New USB device found, idVendor=0403, idProduct=faf0
usb 3-1.2.6: New USB device strings: Mfr=1, Product=2, **SerialNumber=3**
usb 3-1.2.6: Product: APT Piezo Controller
usb 3-1.2.6: Manufacturer: Thorlabs
usb 3-1.2.6: SerialNumber: **81845777**
ftdi_sio 3-1.2.6:1.0: FTDI USB Serial Device converter detected
usb 3-1.2.6: Detected FT232BM
usb 3-1.2.6: FTDI USB Serial Device converter now attached to **ttyUSB5**

I'm trying to do "**pyAPT.Controller(81846609)**" but doesn't work.. I always receive a error -9 or -8 that means (erros that come from ftdi.h library https://www.intra2net.com/en/developer/libftdi/documentation/group__libftdi.html#ga3c5ccb0678b0e268b4081ea978e8eb78)
-8  get product description failed
-9  get serial number failed 

Can anyone help me ?

**Comment by freespace** [comment]
You need to pass the serial as a string not a number.

**Comment by freespace** [comment]
Closing due to lack of further report/activity
